name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions runners are based on Ubuntu

    steps:
      - name: Configure Kali Linux Repository and Update
        run: |
          # Add Kali Linux repository to sources.list
          echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee /etc/apt/sources.list

          # Add Kali Linux keys and update the package list
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys ED444FF07D8D0BF6
          sudo apt update

          # Fix dpkg conflicts and configure
          sudo dpkg-divert --remove /lib32 || true
          sudo dpkg --configure -a

          # Full system upgrade
          sudo apt -y full-upgrade || {
            echo "Upgrade failed. Fixing dependencies...";
            sudo apt --fix-broken install -y;
            sudo apt -y full-upgrade;
          }

      - name: Download and Install Ngrok 3.2
        run: |
          # Download ngrok 3.2 for Linux
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

          # Extract and install ngrok
          tar -xvf ngrok.tgz
          sudo mv ngrok /usr/local/bin/ngrok

      - name: Authenticate Ngrok
        run: |
          if command -v ngrok &> /dev/null; then
            ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          else
            echo "Ngrok is not installed or not in the PATH."
            exit 1
          fi
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Install and Enable RDP (xrdp)
        run: |
          # Install xrdp and XFCE4 desktop environment
          sudo apt install -y xrdp xfce4 xfce4-goodies || {
            echo "Installation failed. Fixing dependencies...";
            sudo apt --fix-broken install -y;
            sudo apt install -y xrdp xfce4 xfce4-goodies;
          }

          # Enable and start xrdp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Check Existing Users
        run: |
          echo "Existing users:"
          cut -d: -f1 /etc/passwd

      - name: Remove Password for User runneradmin (Passwordless Login)
        run: |
          if id "runneradmin" &>/dev/null; then
            sudo passwd -d runneradmin
          else
            echo "User 'runneradmin' not found. Please check the user name."
          fi

      - name: Set Up Auto-Login for xrdp
        run: |
          # Set up XFCE4 as the default session
          echo "startxfce4" > ~/.xsession

          # Modify xrdp.ini to enable console login
          sudo sed -i 's/param=/param=console/' /etc/xrdp/xrdp.ini

      - name: Create Tunnel
        run: |
          if command -v ngrok &> /dev/null; then
            ngrok tcp 3389
          else
            echo "Ngrok is not installed or not in the PATH."
            exit 1
          fi
