name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest  # Kali Linux is based on Ubuntu, so using ubuntu-latest

    steps:
      - name: Download and install ngrok 3.2
        run: |
          # Download ngrok 3.2 for Linux using the provided URL
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

          # Extract the downloaded archive (assuming it's a tar archive)
          tar -xvf ngrok.tgz

          # Move ngrok binary to PATH
          sudo mv ngrok /usr/local/bin/ngrok

      - name: Authenticate Ngrok
        run: |
          if command -v ngrok &> /dev/null; then
            ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          else
            echo "Ngrok is not installed or not in the PATH."
            exit 1
          fi
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Install and Enable RDP (xrdp)
        run: |
          sudo apt update
          sudo apt install -y xrdp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Check existing users
        run: |
          echo "Existing users:"
          cut -d: -f1 /etc/passwd

      - name: Remove password for user runneradmin (Passwordless Login)
        run: |
          if id "runneradmin" &>/dev/null; then
            sudo passwd -d runneradmin
          else
            echo "User 'runneradmin' not found. Please check the user name."
          fi

      - name: Set up auto-login for xrdp
        run: |
          echo "startxfce4" > ~/.xsession
          sudo sed -i 's/param=/param=console/' /etc/xrdp/xrdp.ini

      - name: Create Tunnel
        run: |
          if command -v ngrok &> /dev/null; then
            ngrok tcp 3389
          else
            echo "Ngrok is not installed or not in the PATH."
            exit 1
          fi
