name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions runners are based on Ubuntu

    steps:
      - name: Configure Parrot OS Repository and Update
        run: |
          # Add the correct Parrot OS repository
          echo "deb https://deb.parrot.sh/parrot parrot rolling main contrib non-free" | sudo tee /etc/apt/sources.list.d/parrot.list

          # Add the Parrot OS GPG key
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 5EE1DBA789C809CB

          # Update and upgrade the system
          sudo apt update || { echo "Failed to fetch updates. Please check the repository."; exit 1; }
          sudo apt -y full-upgrade || {
            echo "Upgrade failed. Fixing dependencies...";
            sudo apt --fix-broken install -y;
            sudo apt -y full-upgrade;
          }

      - name: Install Ngrok
        run: |
          # Download ngrok 3.2 for Linux
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

          # Extract and move ngr
