name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest  # Kali Linux is based on Ubuntu, so using ubuntu-latest

    steps:
    - name: Download Ngrok
      run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract Ngrok
      run: unzip ngrok.zip

    - name: Authenticate Ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install and Enable RDP (xrdp)
      run: |
        sudo apt update
        sudo apt install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Check existing users
      run: |
        echo "Existing users:"
        cut -d: -f1 /etc/passwd  # List all users on the system

    - name: Remove password for user kali (Passwordless Login)
      run: |
        if id "kali" &>/dev/null; then
          sudo passwd -d kali  # Remove the password for the kali user
        else
          echo "User 'kali' not found. Please check the user name."
        fi

    - name: Set up auto-login for xrdp
      run: |
        # Create a default X session for the user (to be run when RDP starts)
        echo "startxfce4" > ~/.xsession
        # Modify xrdp to not require a password for login
        sudo sed -i 's/param=/param=console/' /etc/xrdp/xrdp.ini

    - name: Create Tunnel
      run: ./ngrok tcp 3389  # Create an Ngrok tunnel for RDP on port 3389
